version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: partzona-app
    container_name: partzona-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env.docker
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - partzona

  webserver:
    image: nginx:alpine
    container_name: partzona-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - partzona

  mysql:
    image: mysql:8.0
    container_name: partzona-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: partzona_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: partzona_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      # - ./partzone_db_backup.sql:/docker-entrypoint-initdb.d/partzone_db_backup.sql
    ports:
      - "3306:3306"
    networks:
      - partzona

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: partzona-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - partzona

networks:
  partzona:
    driver: bridge

volumes:
  dbdata:
    driver: local